---
# tasks file for vector-role
    - name: Add clickhouse addresses to /etc/hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.clickhouse }}"
    - block:
        - name: Get vector distrib
          ansible.builtin.get_url:
            dest: "./vector-latest-1.x86_64.rpm"
        - name: Install vector package
          become: true
          ansible.builtin.yum:
            name:
              - "./vector-latest-1.x86_64.rpm"

        - name: Redefine vector config name
          tags: vector_config
          become: true
          ansible.builtin.lineinfile:
            path: /etc/default/vector
            regexp: 'VECTOR_CONFIG='
            line: VECTOR_CONFIG=/etc/vector/config.yaml
        - name: Create vector config
          tags: vector_config
          become: true
          ansible.builtin.copy:
            dest: /etc/vector/config.yaml
            content: |
              {{ vector_config | to_nice_yaml(indent=2) }}
