---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    vector_package_name: 'vector'
    vector_service_name: 'vector.service'
  tasks:
  - name: 'Gather Local Services'
    ansible.builtin.service_facts:
    become: true

  - name: 'Assert Vector Service'
    ansible.builtin.assert:
      that:
        - "'{{ vector_service_name }}' in ansible_facts.services"
        - "'running' == ansible_facts.services[vector_service_name].state"
        - "'disabled' == ansible_facts.services[vector_service_name].status"

  - name: 'Gather Installed Packages'
    ansible.builtin.package_facts:
      manager: auto
    become: true

  - name: 'Assert Vector Package'
    ansible.builtin.assert:
      that:
        - "'{{ vector_package_name }}' in ansible_facts.packages"